// <auto-generated />
using System;
using AccountingScholarships.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccountingScholarships.Infrastructure.Migrations.ApplicationDb
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260301121507_NormalizationV2")]
    partial class NormalizationV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.Testing.Auth.AccessRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessRoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.ToTable("AccessRoles");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.Testing.Auth.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.Testing.Auth.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.Testing.Auth.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.Testing.Auth.Scope", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ScopeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Scopes");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.Testing.Auth.UserRoleAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("ScopeId")
                        .HasColumnType("int");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoleAssignments");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bic")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("RecipientBank")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Banks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bic = "CASPKZKA",
                            RecipientBank = "Kaspi Bank"
                        },
                        new
                        {
                            Id = 2,
                            Bic = "HSBKKZKX",
                            RecipientBank = "Halyk Bank"
                        },
                        new
                        {
                            Id = 3,
                            Bic = "TSBNKZKA",
                            RecipientBank = "Jusan Bank"
                        },
                        new
                        {
                            Id = 4,
                            Bic = "IRTYKZKA",
                            RecipientBank = "Forte Bank"
                        },
                        new
                        {
                            Id = 5,
                            Bic = "KCJBKZKX",
                            RecipientBank = "Bank CenterCredit"
                        },
                        new
                        {
                            Id = 6,
                            Bic = "SABRKZKA",
                            RecipientBank = "Bereke Bank"
                        });
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.ChangeHistoryRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FieldLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NewValue")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("StudentIIN")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("StudentIIN");

                    b.ToTable("ChangeHistoryRecords");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.Grant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Conditions")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Grants");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.Scholarship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Conditions")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LostDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("OrderCandidateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("OrderLostDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ScholarshipTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ScholarshipTypeId");

                    b.HasIndex("StudentId");

                    b.ToTable("Scholarships");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.ScholarshipLossRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("IIN")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("LostDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OrderNumber")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ScholarshipName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IIN");

                    b.HasIndex("StudentId");

                    b.ToTable("ScholarshipLossRecords");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.ScholarshipType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ScholarshipName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("ScholarshipTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ScholarshipName = "Государственная стипендия"
                        });
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.StatusStudentHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StatusTypeId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("StatusTypeId");

                    b.HasIndex("StudentId");

                    b.ToTable("StatusStudentHistories");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.StatusType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("StatusTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StatusName = "Активный"
                        },
                        new
                        {
                            Id = 2,
                            StatusName = "Академический отпуск"
                        },
                        new
                        {
                            Id = 3,
                            StatusName = "Отчислен"
                        },
                        new
                        {
                            Id = 4,
                            StatusName = "Выпускник"
                        },
                        new
                        {
                            Id = 5,
                            StatusName = "Переведён"
                        });
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BankId")
                        .HasColumnType("int");

                    b.Property<int>("Course")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DegreeLevelId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("GroupName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IIN")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Sex")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("SpecialityId")
                        .HasColumnType("int");

                    b.Property<int?>("StudyFormId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("iban")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("varchar(34)");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("DegreeLevelId");

                    b.HasIndex("Email");

                    b.HasIndex("IIN")
                        .IsUnique();

                    b.HasIndex("SpecialityId");

                    b.HasIndex("StudyFormId");

                    b.HasIndex("iban")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.Testing.StudentData.DegreeLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DegreeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("DegreeLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DegreeName = "Бакалавриат"
                        },
                        new
                        {
                            Id = 2,
                            DegreeName = "Магистратура"
                        },
                        new
                        {
                            Id = 3,
                            DegreeName = "Докторантура"
                        });
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.Testing.StudentData.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentHead")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<int>("InstituteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstituteId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentName = "ПИ",
                            InstituteId = 2
                        },
                        new
                        {
                            Id = 2,
                            DepartmentName = "АиУ",
                            InstituteId = 2
                        },
                        new
                        {
                            Id = 3,
                            DepartmentName = "ЭТиКТ",
                            InstituteId = 2
                        },
                        new
                        {
                            Id = 4,
                            DepartmentName = "КОиХИ",
                            InstituteId = 2
                        },
                        new
                        {
                            Id = 5,
                            DepartmentName = "РТиТСА",
                            InstituteId = 2
                        },
                        new
                        {
                            Id = 6,
                            DepartmentName = "ВМиМ",
                            InstituteId = 2
                        },
                        new
                        {
                            Id = 7,
                            DepartmentName = "КБ",
                            InstituteId = 2
                        },
                        new
                        {
                            Id = 8,
                            DepartmentName = "ИС",
                            InstituteId = 2
                        },
                        new
                        {
                            Id = 9,
                            DepartmentName = "ИСиС",
                            InstituteId = 1
                        },
                        new
                        {
                            Id = 10,
                            DepartmentName = "СиСМ",
                            InstituteId = 1
                        },
                        new
                        {
                            Id = 11,
                            DepartmentName = "Академия дизайна",
                            InstituteId = 1
                        },
                        new
                        {
                            Id = 12,
                            DepartmentName = "Студенческое конструкторское бюро",
                            InstituteId = 1
                        },
                        new
                        {
                            Id = 13,
                            DepartmentName = "МДиГ",
                            InstituteId = 3
                        },
                        new
                        {
                            Id = 14,
                            DepartmentName = "ГД",
                            InstituteId = 3
                        },
                        new
                        {
                            Id = 15,
                            DepartmentName = "МНиИФ",
                            InstituteId = 3
                        },
                        new
                        {
                            Id = 16,
                            DepartmentName = "МиОПИ",
                            InstituteId = 3
                        },
                        new
                        {
                            Id = 17,
                            DepartmentName = "ХПиПЭ",
                            InstituteId = 3
                        },
                        new
                        {
                            Id = 18,
                            DepartmentName = "ИЦГ",
                            InstituteId = 3
                        },
                        new
                        {
                            Id = 19,
                            DepartmentName = "Энергетика",
                            InstituteId = 4
                        },
                        new
                        {
                            Id = 20,
                            DepartmentName = "ИМ",
                            InstituteId = 4
                        },
                        new
                        {
                            Id = 21,
                            DepartmentName = "ССиМ",
                            InstituteId = 4
                        },
                        new
                        {
                            Id = 22,
                            DepartmentName = "МС",
                            InstituteId = 4
                        },
                        new
                        {
                            Id = 23,
                            DepartmentName = "ОФ",
                            InstituteId = 4
                        },
                        new
                        {
                            Id = 24,
                            DepartmentName = "ТМиО",
                            InstituteId = 4
                        },
                        new
                        {
                            Id = 25,
                            DepartmentName = "ТМиГТУ",
                            InstituteId = 4
                        },
                        new
                        {
                            Id = 26,
                            DepartmentName = "ФкМ",
                            InstituteId = 4
                        },
                        new
                        {
                            Id = 27,
                            DepartmentName = "РиМВМ",
                            InstituteId = 4
                        },
                        new
                        {
                            Id = 28,
                            DepartmentName = "ГСПиРМПИ",
                            InstituteId = 5
                        },
                        new
                        {
                            Id = 29,
                            DepartmentName = "НИ",
                            InstituteId = 5
                        },
                        new
                        {
                            Id = 30,
                            DepartmentName = "ГС",
                            InstituteId = 5
                        },
                        new
                        {
                            Id = 31,
                            DepartmentName = "ГИиНГ",
                            InstituteId = 5
                        },
                        new
                        {
                            Id = 32,
                            DepartmentName = "ХиБИ",
                            InstituteId = 5
                        },
                        new
                        {
                            Id = 33,
                            DepartmentName = "Логистика",
                            InstituteId = 6
                        },
                        new
                        {
                            Id = 34,
                            DepartmentName = "Транспортная инженерия",
                            InstituteId = 6
                        },
                        new
                        {
                            Id = 35,
                            DepartmentName = "ШТИиЛ",
                            InstituteId = 6
                        },
                        new
                        {
                            Id = 36,
                            DepartmentName = "Бизнес-школа",
                            InstituteId = 7
                        });
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.Testing.StudentData.Institute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("InstituteDirector")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("InstituteName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Institutes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InstituteName = "ИАиС"
                        },
                        new
                        {
                            Id = 2,
                            InstituteName = "Институт автоматики и информационных технологий"
                        },
                        new
                        {
                            Id = 3,
                            InstituteName = "Горно-металлургический институт имени О.Байконурова"
                        },
                        new
                        {
                            Id = 4,
                            InstituteName = "ИЭиМ"
                        },
                        new
                        {
                            Id = 5,
                            InstituteName = "ИГНД"
                        },
                        new
                        {
                            Id = 6,
                            InstituteName = "ШТИиЛ"
                        },
                        new
                        {
                            Id = 7,
                            InstituteName = "БШ"
                        });
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.Testing.StudentData.Speciality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("SpecialityName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Specialities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            SpecialityName = "Программная инженерия"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            SpecialityName = "Автоматизация и управление"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            SpecialityName = "Электронная техника и коммуникационные технологии"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 4,
                            SpecialityName = "Компьютерная оптика и химическое инженерство"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 5,
                            SpecialityName = "Радиотехника и телекоммуникации"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 6,
                            SpecialityName = "Вычислительная математика и моделирование"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 7,
                            SpecialityName = "Кибербезопасность"
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 8,
                            SpecialityName = "Информационные системы"
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 9,
                            SpecialityName = "Инженерные системы и сети"
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 10,
                            SpecialityName = "Строительство и строительные материалы"
                        },
                        new
                        {
                            Id = 11,
                            DepartmentId = 11,
                            SpecialityName = "Дизайн"
                        },
                        new
                        {
                            Id = 12,
                            DepartmentId = 12,
                            SpecialityName = "Конструирование"
                        },
                        new
                        {
                            Id = 13,
                            DepartmentId = 13,
                            SpecialityName = "Металлургия и горное дело"
                        },
                        new
                        {
                            Id = 14,
                            DepartmentId = 14,
                            SpecialityName = "Горное дело"
                        },
                        new
                        {
                            Id = 15,
                            DepartmentId = 15,
                            SpecialityName = "Металлургия наноматериалов"
                        },
                        new
                        {
                            Id = 16,
                            DepartmentId = 16,
                            SpecialityName = "Металлургия и обогащение полезных ископаемых"
                        },
                        new
                        {
                            Id = 17,
                            DepartmentId = 17,
                            SpecialityName = "Химическое производство и промышленная экология"
                        },
                        new
                        {
                            Id = 18,
                            DepartmentId = 18,
                            SpecialityName = "Инженерная и компьютерная графика"
                        },
                        new
                        {
                            Id = 19,
                            DepartmentId = 19,
                            SpecialityName = "Энергетика"
                        },
                        new
                        {
                            Id = 20,
                            DepartmentId = 20,
                            SpecialityName = "Инженерная механика"
                        },
                        new
                        {
                            Id = 21,
                            DepartmentId = 21,
                            SpecialityName = "Стандартизация, сертификация и метрология"
                        },
                        new
                        {
                            Id = 22,
                            DepartmentId = 22,
                            SpecialityName = "Машиностроение"
                        },
                        new
                        {
                            Id = 23,
                            DepartmentId = 23,
                            SpecialityName = "Обогащение и флотация"
                        },
                        new
                        {
                            Id = 24,
                            DepartmentId = 24,
                            SpecialityName = "Технология машиностроения и оборудования"
                        },
                        new
                        {
                            Id = 25,
                            DepartmentId = 25,
                            SpecialityName = "Теплотехника и газотурбинные установки"
                        },
                        new
                        {
                            Id = 26,
                            DepartmentId = 26,
                            SpecialityName = "Физика конденсированного состояния и материаловедение"
                        },
                        new
                        {
                            Id = 27,
                            DepartmentId = 27,
                            SpecialityName = "Робототехника и мехатроника"
                        },
                        new
                        {
                            Id = 28,
                            DepartmentId = 28,
                            SpecialityName = "Геология и разведка месторождений"
                        },
                        new
                        {
                            Id = 29,
                            DepartmentId = 29,
                            SpecialityName = "Нефтяное инженерство"
                        },
                        new
                        {
                            Id = 30,
                            DepartmentId = 30,
                            SpecialityName = "Геодезия и съёмка"
                        },
                        new
                        {
                            Id = 31,
                            DepartmentId = 31,
                            SpecialityName = "Геоинформатика и нефтегазовое дело"
                        },
                        new
                        {
                            Id = 32,
                            DepartmentId = 32,
                            SpecialityName = "Химия и биоинженерия"
                        },
                        new
                        {
                            Id = 33,
                            DepartmentId = 33,
                            SpecialityName = "Логистика"
                        },
                        new
                        {
                            Id = 34,
                            DepartmentId = 34,
                            SpecialityName = "Транспортная инженерия"
                        },
                        new
                        {
                            Id = 35,
                            DepartmentId = 35,
                            SpecialityName = "Транспортные технологии и логистика"
                        },
                        new
                        {
                            Id = 36,
                            DepartmentId = 36,
                            SpecialityName = "Бизнес и предпринимательство"
                        });
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.Testing.StudentData.StudyForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("StudyFormName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("StudyForms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StudyFormName = "Очная"
                        },
                        new
                        {
                            Id = 2,
                            StudyFormName = "Онлайн"
                        });
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.StudentGrant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GrantId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("GrantId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentGrants");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.StudentScholarship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("ScholarshipId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ScholarshipId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentScholarships");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.UserActionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserActionHistories");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.Testing.Auth.RolePermission", b =>
                {
                    b.HasOne("AccountingScholarships.Domain.Entities.Testing.Auth.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccountingScholarships.Domain.Entities.Testing.Auth.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.Testing.Auth.UserRoleAssignment", b =>
                {
                    b.HasOne("AccountingScholarships.Domain.Entities.Testing.Auth.Role", "Role")
                        .WithMany("UserAssignments")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccountingScholarships.Domain.Entities.User", "User")
                        .WithMany("UserAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.Grant", b =>
                {
                    b.HasOne("AccountingScholarships.Domain.Entities.Student", "Student")
                        .WithMany("Grants")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.Scholarship", b =>
                {
                    b.HasOne("AccountingScholarships.Domain.Entities.ScholarshipType", "ScholarshipTypeRef")
                        .WithMany("Scholarships")
                        .HasForeignKey("ScholarshipTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AccountingScholarships.Domain.Entities.Student", "Student")
                        .WithMany("Scholarships")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScholarshipTypeRef");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.ScholarshipLossRecord", b =>
                {
                    b.HasOne("AccountingScholarships.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.StatusStudentHistory", b =>
                {
                    b.HasOne("AccountingScholarships.Domain.Entities.StatusType", "StatusType")
                        .WithMany("StatusHistories")
                        .HasForeignKey("StatusTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccountingScholarships.Domain.Entities.Student", "Student")
                        .WithMany("StatusHistories")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatusType");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.Student", b =>
                {
                    b.HasOne("AccountingScholarships.Domain.Entities.Bank", "Bank")
                        .WithMany("Students")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AccountingScholarships.Domain.Entities.Testing.StudentData.DegreeLevel", "DegreeLevel")
                        .WithMany("Students")
                        .HasForeignKey("DegreeLevelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AccountingScholarships.Domain.Entities.Testing.StudentData.Speciality", "Speciality")
                        .WithMany("Students")
                        .HasForeignKey("SpecialityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AccountingScholarships.Domain.Entities.Testing.StudentData.StudyForm", "StudyForm")
                        .WithMany("Students")
                        .HasForeignKey("StudyFormId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Bank");

                    b.Navigation("DegreeLevel");

                    b.Navigation("Speciality");

                    b.Navigation("StudyForm");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.Testing.StudentData.Department", b =>
                {
                    b.HasOne("AccountingScholarships.Domain.Entities.Testing.StudentData.Institute", "Institute")
                        .WithMany("Departments")
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institute");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.Testing.StudentData.Speciality", b =>
                {
                    b.HasOne("AccountingScholarships.Domain.Entities.Testing.StudentData.Department", "Department")
                        .WithMany("Specialities")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.StudentGrant", b =>
                {
                    b.HasOne("AccountingScholarships.Domain.Entities.Grant", "Grant")
                        .WithMany("StudentGrants")
                        .HasForeignKey("GrantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccountingScholarships.Domain.Entities.Student", "Student")
                        .WithMany("StudentGrants")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grant");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.StudentScholarship", b =>
                {
                    b.HasOne("AccountingScholarships.Domain.Entities.Scholarship", "Scholarship")
                        .WithMany("StudentScholarships")
                        .HasForeignKey("ScholarshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccountingScholarships.Domain.Entities.Student", "Student")
                        .WithMany("StudentScholarships")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scholarship");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.UserActionHistory", b =>
                {
                    b.HasOne("AccountingScholarships.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.Testing.Auth.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.Testing.Auth.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserAssignments");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.Bank", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.Grant", b =>
                {
                    b.Navigation("StudentGrants");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.Scholarship", b =>
                {
                    b.Navigation("StudentScholarships");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.ScholarshipType", b =>
                {
                    b.Navigation("Scholarships");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.StatusType", b =>
                {
                    b.Navigation("StatusHistories");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.Student", b =>
                {
                    b.Navigation("Grants");

                    b.Navigation("Scholarships");

                    b.Navigation("StatusHistories");

                    b.Navigation("StudentGrants");

                    b.Navigation("StudentScholarships");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.Testing.StudentData.DegreeLevel", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.Testing.StudentData.Department", b =>
                {
                    b.Navigation("Specialities");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.Testing.StudentData.Institute", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.Testing.StudentData.Speciality", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.Testing.StudentData.StudyForm", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.User", b =>
                {
                    b.Navigation("UserAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
