// <auto-generated />
using System;
using AccountingScholarships.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccountingScholarships.Infrastructure.Migrations.EpvoDb
{
    [DbContext(typeof(EpvoDbContext))]
    [Migration("20260210112608_InitialEpvoCreate")]
    partial class InitialEpvoCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AccountingScholarships.Domain.Entities.Epvo.EpvoStudent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Course")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Faculty")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("GrantAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GrantName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("IIN")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("ScholarshipAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ScholarshipName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Speciality")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("SyncDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IIN")
                        .IsUnique();

                    b.ToTable("EpvoStudents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Course = 4,
                            DateOfBirth = new DateTime(2003, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Faculty = "Информационные технологии",
                            FirstName = "Алихан",
                            GrantAmount = 500000m,
                            GrantName = "Государственный грант",
                            IIN = "030515500123",
                            IsActive = true,
                            LastName = "Сериков",
                            MiddleName = "Бауржанович",
                            ScholarshipAmount = 36660m,
                            ScholarshipName = "Академическая стипендия",
                            Speciality = "Программная инженерия",
                            SyncDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            Course = 3,
                            DateOfBirth = new DateTime(2004, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Faculty = "Экономика",
                            FirstName = "Айгерим",
                            GrantAmount = 450000m,
                            GrantName = "Государственный грант",
                            IIN = "040820600456",
                            IsActive = true,
                            LastName = "Нурланова",
                            MiddleName = "Ерлановна",
                            ScholarshipAmount = 50000m,
                            ScholarshipName = "Повышенная стипендия",
                            Speciality = "Финансы",
                            SyncDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            Course = 2,
                            DateOfBirth = new DateTime(2002, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Faculty = "Юриспруденция",
                            FirstName = "Дамир",
                            GrantAmount = 400000m,
                            GrantName = "Государственный грант",
                            IIN = "020110500789",
                            IsActive = true,
                            LastName = "Касымов",
                            Speciality = "Правоведение",
                            SyncDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-0123-defa-234567890123"),
                            Course = 1,
                            DateOfBirth = new DateTime(2005, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Faculty = "Информационные технологии",
                            FirstName = "Мадина",
                            IIN = "050305700234",
                            IsActive = true,
                            LastName = "Абдрахманова",
                            MiddleName = "Канатовна",
                            Speciality = "Информационная безопасность",
                            SyncDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-c9d0-1234-efab-345678901234"),
                            Course = 4,
                            DateOfBirth = new DateTime(2001, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Faculty = "Медицина",
                            FirstName = "Нурсултан",
                            GrantAmount = 600000m,
                            GrantName = "Государственный грант",
                            IIN = "010725500567",
                            IsActive = false,
                            LastName = "Токаев",
                            MiddleName = "Маратович",
                            ScholarshipAmount = 36660m,
                            ScholarshipName = "Академическая стипендия",
                            Speciality = "Общая медицина",
                            SyncDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
